# Generated by Django 2.0.7 on 2020-02-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Establece verdadero cuando el usuario haya verificado su email', verbose_name='verificado'),
        ),
    ]
