# Generated by Django 2.0.7 on 2020-02-07 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en la cual se modifico el objeto', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora en la cual se modifico el objeto', verbose_name='modified at')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='ttulo del album')),
                ('description', models.TextField(blank=True, help_text='Descripcion del Album', max_length=250, null=True)),
                ('year', models.PositiveSmallIntegerField(default=0, help_text='Anio de publicacion de album', verbose_name='year')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='albums/portadas/', verbose_name='foto de portada')),
                ('artist', models.ForeignKey(help_text='Artista que pertenece el album', on_delete=django.db.models.deletion.CASCADE, to='artists.Artist')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
